-- PSGC province/city normalization script generated from psgc_province_city_fixes.csv
-- MySQL 1093-safe and safe to re-run: updates are idempotent and preserve FK integrity.
START TRANSACTION;

-- Fix #1: ProvinceCode 0330100000, CityCode 0330100000
SET @bad_province_code='0330100000'; SET @city_code='0330100000'; SET @target_province_name='Pampanga'; SET @target_city_name='Angeles'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #2: ProvinceCode 0331400000, CityCode 0331400000
SET @bad_province_code='0331400000'; SET @city_code='0331400000'; SET @target_province_name='Zambales'; SET @target_city_name='Olongapo'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #3: ProvinceCode 0431200000, CityCode 0431200000
SET @bad_province_code='0431200000'; SET @city_code='0431200000'; SET @target_province_name='Quezon'; SET @target_city_name='Lucena'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #4: ProvinceCode 0630200000, CityCode 0630200000
SET @bad_province_code='0630200000'; SET @city_code='0630200000'; SET @target_province_name='Negros Occidental'; SET @target_city_name='Bacolod'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #5: ProvinceCode 0631000000, CityCode 0631000000
SET @bad_province_code='0631000000'; SET @city_code='0631000000'; SET @target_province_name='Iloilo'; SET @target_city_name='Iloilo'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #6: ProvinceCode 0730600000, CityCode 0730600000
SET @bad_province_code='0730600000'; SET @city_code='0730600000'; SET @target_province_name='Cebu'; SET @target_city_name='Cebu'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #7: ProvinceCode 0731100000, CityCode 0731100000
SET @bad_province_code='0731100000'; SET @city_code='0731100000'; SET @target_province_name='Cebu'; SET @target_city_name='Lapu-Lapu'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #8: ProvinceCode 0731300000, CityCode 0731300000
SET @bad_province_code='0731300000'; SET @city_code='0731300000'; SET @target_province_name='Cebu'; SET @target_city_name='Mandaue'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #9: ProvinceCode 0831600000, CityCode 0831600000
SET @bad_province_code='0831600000'; SET @city_code='0831600000'; SET @target_province_name='Leyte'; SET @target_city_name='Tacloban'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #10: ProvinceCode 0931700000, CityCode 0931700000
SET @bad_province_code='0931700000'; SET @city_code='0931700000'; SET @target_province_name='Zamboanga del Sur'; SET @target_city_name='Zamboanga'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #11: ProvinceCode 0990100000, CityCode 0990101000
SET @bad_province_code='0990100000'; SET @city_code='0990101000'; SET @target_province_name='Basilan'; SET @target_city_name='Isabela'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #12: ProvinceCode 1030500000, CityCode 1030500000
SET @bad_province_code='1030500000'; SET @city_code='1030500000'; SET @target_province_name='Misamis Oriental'; SET @target_city_name='Cagayan de Oro'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #13: ProvinceCode 1030900000, CityCode 1030900000
SET @bad_province_code='1030900000'; SET @city_code='1030900000'; SET @target_province_name='Lanao del Norte'; SET @target_city_name='Iligan'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #14: ProvinceCode 1130700000, CityCode 1130700000
SET @bad_province_code='1130700000'; SET @city_code='1130700000'; SET @target_province_name='Davao del Sur'; SET @target_city_name='Davao'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

COMMIT;

-- Post-update verification per city
-- Verify #1
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0330100000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #2
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0331400000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #3
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0431200000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #4
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0630200000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #5
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0631000000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #6
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0730600000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #7
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0731100000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #8
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0731300000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #9
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0831600000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #10
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0931700000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #11
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='0990101000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #12
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1030500000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #13
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1030900000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #14
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1130700000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Global sanity check: remaining synthetic province labels
SELECT ProvinceCode, ProvinceName FROM psgcprovinces WHERE ProvinceName LIKE 'Province %' ORDER BY ProvinceCode;

-- Global sanity check: city records still prefixed by 'City of '
SELECT CityMunicipalityCode, CityMunicipalityName FROM psgccitiesmunicipalities WHERE CityMunicipalityName LIKE 'City of %' ORDER BY CityMunicipalityCode;


