-- PSGC province/city normalization script generated from psgc_province_city_fixes_2_ascii.csv
-- MySQL 1093-safe and ASCII-safe variant.
START TRANSACTION;

-- Fix #1: ProvinceCode 1230800000, CityCode 1230800000
SET @bad_province_code='1230800000'; SET @city_code='1230800000'; SET @target_province_name='South Cotabato'; SET @target_city_name='General Santos City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #2: ProvinceCode 1380100000, CityCode 1380100000
SET @bad_province_code='1380100000'; SET @city_code='1380100000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Caloocan City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #3: ProvinceCode 1380200000, CityCode 1380200000
SET @bad_province_code='1380200000'; SET @city_code='1380200000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Las Pinas City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #4: ProvinceCode 1380300000, CityCode 1380300000
SET @bad_province_code='1380300000'; SET @city_code='1380300000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Makati City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #5: ProvinceCode 1380400000, CityCode 1380400000
SET @bad_province_code='1380400000'; SET @city_code='1380400000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Malabon City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #6: ProvinceCode 1380500000, CityCode 1380500000
SET @bad_province_code='1380500000'; SET @city_code='1380500000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Mandaluyong City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #7: ProvinceCode 1380600000, CityCode 1380600000
SET @bad_province_code='1380600000'; SET @city_code='1380600000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Manila'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #8: ProvinceCode 1380600000, CityCode 1380601000
SET @bad_province_code='1380600000'; SET @city_code='1380601000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Tondo I/II'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #9: ProvinceCode 1380600000, CityCode 1380602000
SET @bad_province_code='1380600000'; SET @city_code='1380602000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Binondo'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #10: ProvinceCode 1380600000, CityCode 1380603000
SET @bad_province_code='1380600000'; SET @city_code='1380603000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Quiapo'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #11: ProvinceCode 1380600000, CityCode 1380604000
SET @bad_province_code='1380600000'; SET @city_code='1380604000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='San Nicolas'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #12: ProvinceCode 1380600000, CityCode 1380605000
SET @bad_province_code='1380600000'; SET @city_code='1380605000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Santa Cruz'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #13: ProvinceCode 1380600000, CityCode 1380606000
SET @bad_province_code='1380600000'; SET @city_code='1380606000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Sampaloc'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #14: ProvinceCode 1380600000, CityCode 1380607000
SET @bad_province_code='1380600000'; SET @city_code='1380607000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='San Miguel'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #15: ProvinceCode 1380600000, CityCode 1380608000
SET @bad_province_code='1380600000'; SET @city_code='1380608000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Ermita'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #16: ProvinceCode 1380600000, CityCode 1380609000
SET @bad_province_code='1380600000'; SET @city_code='1380609000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Intramuros'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #17: ProvinceCode 1380600000, CityCode 1380610000
SET @bad_province_code='1380600000'; SET @city_code='1380610000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Malate'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

COMMIT;

-- Post-update verification per city
-- Verify #1
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1230800000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #2
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380100000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #3
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380200000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #4
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380300000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #5
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380400000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #6
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380500000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #7
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380600000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #8
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380601000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #9
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380602000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #10
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380603000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #11
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380604000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #12
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380605000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #13
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380606000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #14
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380607000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #15
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380608000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #16
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380609000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Verify #17
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380610000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Global sanity check: remaining synthetic province labels
SELECT ProvinceCode, ProvinceName FROM psgcprovinces WHERE ProvinceName LIKE 'Province %' ORDER BY ProvinceCode;

-- Global sanity check: city records still prefixed by 'City of '
SELECT CityMunicipalityCode, CityMunicipalityName FROM psgccitiesmunicipalities WHERE CityMunicipalityName LIKE 'City of %' ORDER BY CityMunicipalityCode;
