-- PSGC province/city normalization script generated from WeirdProvinceNames3.csv
-- MySQL 1093-safe and ASCII-safe variant.
START TRANSACTION;

-- Fix #1: ProvinceCode 1380600000, CityCode 1380611000
SET @bad_province_code='1380600000'; SET @city_code='1380611000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Paco'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #2: ProvinceCode 1380600000, CityCode 1380612000
SET @bad_province_code='1380600000'; SET @city_code='1380612000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Pandacan'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #3: ProvinceCode 1380600000, CityCode 1380613000
SET @bad_province_code='1380600000'; SET @city_code='1380613000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Port Area'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #4: ProvinceCode 1380600000, CityCode 1380614000
SET @bad_province_code='1380600000'; SET @city_code='1380614000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Santa Ana'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #5: ProvinceCode 1380700000, CityCode 1380700000
SET @bad_province_code='1380700000'; SET @city_code='1380700000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Marikina City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #6: ProvinceCode 1380800000, CityCode 1380800000
SET @bad_province_code='1380800000'; SET @city_code='1380800000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Muntinlupa City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #7: ProvinceCode 1380900000, CityCode 1380900000
SET @bad_province_code='1380900000'; SET @city_code='1380900000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Navotas City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #8: ProvinceCode 1381000000, CityCode 1381000000
SET @bad_province_code='1381000000'; SET @city_code='1381000000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Paranaque City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #9: ProvinceCode 1381100000, CityCode 1381100000
SET @bad_province_code='1381100000'; SET @city_code='1381100000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Pasay City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #10: ProvinceCode 1381200000, CityCode 1381200000
SET @bad_province_code='1381200000'; SET @city_code='1381200000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Pasig City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #11: ProvinceCode 1381300000, CityCode 1381300000
SET @bad_province_code='1381300000'; SET @city_code='1381300000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Quezon City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #12: ProvinceCode 1381400000, CityCode 1381400000
SET @bad_province_code='1381400000'; SET @city_code='1381400000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='San Juan City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #13: ProvinceCode 1381500000, CityCode 1381500000
SET @bad_province_code='1381500000'; SET @city_code='1381500000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Taguig City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #14: ProvinceCode 1381600000, CityCode 1381600000
SET @bad_province_code='1381600000'; SET @city_code='1381600000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Valenzuela City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #15: ProvinceCode 1381700000, CityCode 1381701000
SET @bad_province_code='1381700000'; SET @city_code='1381701000'; SET @target_province_name='Metropolitan Manila'; SET @target_city_name='Pateros'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #16: ProvinceCode 1430300000, CityCode 1430300000
SET @bad_province_code='1430300000'; SET @city_code='1430300000'; SET @target_province_name='Benguet'; SET @target_city_name='Baguio City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #17: ProvinceCode 1630400000, CityCode 1630400000
SET @bad_province_code='1630400000'; SET @city_code='1630400000'; SET @target_province_name='Agusan del Norte'; SET @target_city_name='Butuan City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

-- Fix #18: ProvinceCode 1731500000, CityCode 1731500000
SET @bad_province_code='1731500000'; SET @city_code='1731500000'; SET @target_province_name='Palawan'; SET @target_city_name='Puerto Princesa City'; SET @existing_province_code=(SELECT ProvinceCode FROM psgcprovinces WHERE TRIM(ProvinceName)=@target_province_name ORDER BY ProvinceCode LIMIT 1); UPDATE psgcprovinces SET ProvinceName=@target_province_name WHERE ProvinceCode=@bad_province_code AND (@existing_province_code IS NULL OR @existing_province_code=@bad_province_code); UPDATE psgccitiesmunicipalities SET ProvinceCode=COALESCE(@existing_province_code,@bad_province_code), CityMunicipalityName=@target_city_name WHERE CityMunicipalityCode=@city_code; DELETE FROM psgcprovinces WHERE ProvinceCode=@bad_province_code AND @existing_province_code IS NOT NULL AND @existing_province_code<>@bad_province_code AND NOT EXISTS (SELECT 1 FROM psgccitiesmunicipalities WHERE ProvinceCode=@bad_province_code);

COMMIT;

-- Post-update verification per city
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380611000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380612000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380613000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380614000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380700000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380800000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1380900000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381000000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381100000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381200000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381300000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381400000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381500000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381600000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1381701000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1430300000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1630400000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;
SELECT c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName,COUNT(b.BarangayCode) AS BarangayCount FROM psgccitiesmunicipalities c JOIN psgcprovinces p ON p.ProvinceCode=c.ProvinceCode LEFT JOIN psgcbarangays b ON b.CityMunicipalityCode=c.CityMunicipalityCode WHERE c.CityMunicipalityCode='1731500000' GROUP BY c.CityMunicipalityCode,c.CityMunicipalityName,c.ProvinceCode,p.ProvinceName;

-- Global sanity checks
SELECT ProvinceCode, ProvinceName FROM psgcprovinces WHERE ProvinceName LIKE 'Province %' ORDER BY ProvinceCode;
SELECT CityMunicipalityCode, CityMunicipalityName FROM psgccitiesmunicipalities WHERE CityMunicipalityName LIKE 'City of %' ORDER BY CityMunicipalityCode;
